site_name: STI2D Jules Verne
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: fr

  icon:
    admonition:
      <type>: <icon>

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to lignt mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/phmorin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/phmorin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/phmorin

copyright: >
    Documents <a href="https://github.com/phmorin" target="_blank">Philippe MORIN</a>
    &copy; 2021 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>


markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

